"use client";

import { Card, CardBody, CardHeader, CardFooter } from "@heroui/card";
import { Chip } from "@heroui/chip";
import { Divider } from "@heroui/divider";
import { IngredientsList } from "./IngredientsList";
import { StepsAccordion } from "./StepsAccordion";
import { MealSuggestion } from "@/context/ChefContext";

export const MealCard = ({ meal }: { meal: MealSuggestion }) => {
    return (
        <Card className="w-full max-w-3xl shadow-2xl">
            <CardHeader className="flex flex-col items-start px-6 pt-6 pb-0">
                <div className="flex justify-between w-full items-start mb-2">
                    <h2 className="text-3xl font-bold text-primary">{meal.title}</h2>
                    <Chip color="warning" variant="shadow">{meal.difficulty}</Chip>
                </div>
                <p className="text-default-500 text-lg mb-4">{meal.summary}</p>
                <div className="flex gap-2 flex-wrap mb-4">
                    {meal.whyItFits.map((reason, idx) => (
                        <Chip key={idx} size="sm" variant="flat" color="success">
                            {reason}
                        </Chip>
                    ))}
                    <Chip size="sm" variant="flat" color="secondary">
                        {meal.estimatedTimeMinutes} mins
                    </Chip>
                </div>
            </CardHeader>

            <Divider />

            <CardBody className="px-6 py-4 gap-8">
                <div className="grid md:grid-cols-2 gap-8">
                    <div>
                        <h3 className="text-xl font-bold mb-4 flex items-center gap-2">
                            🛒 Ingredients
                        </h3>
                        <IngredientsList ingredients={meal.ingredients} />
                    </div>

                    <div>
                        <h3 className="text-xl font-bold mb-4 flex items-center gap-2">
                            👩‍🍳 Instructions
                        </h3>
                        <StepsAccordion steps={meal.steps} />
                    </div>
                </div>
            </CardBody>

            <CardFooter className="px-6 pb-6 pt-4 justify-center">
                <p className="text-small text-default-400">
                    Generated by ChefUp AI • Enjoy your meal!
                </p>
            </CardFooter>
        </Card>
    );
};
